name: Continuous Deploy #action名称
on: [push] #在推送的时候运行此action

jobs:
  deploy_job:
    runs-on: ubuntu-latest  #运行环境
    name: build
    steps:
      # check out the repository
      - name: Checkout    
        uses: actions/checkout@v2    #这里使用了github官方提供的action,checkout项目到虚拟机上

      - name: Build
        run: |
          cd frontend
          npm install
          npm run build

      - name: deploy file to server
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:  
          username: 'powcai_top'   #ftp user name
          server: '101.43.104.15' #引用之前创建好的secret
          password: ${{ secrets.FTP_PASSWORD }} #引用之前创建好的secret
          local-dir: './frontend/dist/'  # 对应我们项目build的文件夹路径
          server-dir: '/www/wwwroot/powcai.top/'
